# Generated by Django 2.0.4 on 2018-04-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdjacencyList', models.CharField(max_length=200)),
                ('GA_SOLUTION_FILE', models.CharField(max_length=200)),
                ('CHROMOSOME_FILE', models.CharField(max_length=200)),
                ('METRIC_OUTPUT', models.CharField(max_length=200)),
                ('GENOTYPE_SIZE', models.IntegerField(default=10)),
                ('STEP_SIZE', models.IntegerField(default=1)),
                ('PURGE_DELAY', models.IntegerField(default=10000)),
                ('SAMPLE_RATE', models.IntegerField(default=10000)),
            ],
        ),
    ]
