# Generated by Django 2.0.4 on 2018-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='CONFIG_FILE',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
